"""
Django settings for tbd_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-3n@^hg0@wmx1t$lw2xkr2m0dbh_5r3o5dc#&l8g4=q#eg^z1ph')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# In development accept any host so the dev machine's LAN IP can change
# freely; production must set the ALLOWED_HOSTS env var explicitly.
_default_hosts = '*' if DEBUG else 'localhost,127.0.0.1'
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=_default_hosts, cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be at the top for channels
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'channels',
    'corsheaders',
    
    # Local apps
    'users',
    'posts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tbd_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tbd_backend.wsgi.application'
ASGI_APPLICATION = 'tbd_backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Production runs Postgres (DATABASE_URL, e.g. postgres:///cmim over the local
# socket); local dev stays on SQLite. CONN_MAX_AGE=0: under ASGI sync views run
# in a thread pool, and persistent per-thread connections leak - local socket
# connects cost ~1ms.
DATABASE_URL = config('DATABASE_URL', default='')
if DATABASE_URL:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=0, conn_health_checks=True),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# The cache backs DRF throttling. The default LocMemCache holds 300 keys per
# process, so past ~150 active clients rate-limit history was evicted (limits
# silently reset), and it was never shared between worker processes. Redis
# when CACHE_URL is set (production), in-memory for dev and tests.
CACHE_URL = config('CACHE_URL', default='')
if CACHE_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': CACHE_URL,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Channels configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [config('REDIS_URL', default='redis://localhost:6379')],
        },
    },
}

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'posts.throttles.RealIPThrottle',
        'posts.throttles.DeviceThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/hour',          # per real client IP (carrier NAT shares IPs)
        'user': '300/hour',           # per device id
        'post_create': '10/hour',     # per device id - the product rule
        'post_create_ip': '60/hour',  # per IP - stops device-id rotation
    }
}

# CORS settings for frontend. Only browsers enforce CORS (Expo web); the
# native app ignores it. Allow everything in development so the dev machine's
# LAN IP can change freely.
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:19006",
        "http://localhost:19000",
    ]

CORS_ALLOW_CREDENTIALS = True

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# S3 media (production): rendered PNGs go to the public-read bucket and are
# served directly from S3. Dev default stays on local disk. Credentials come
# from the environment / ~/.aws the standard boto3 way.
USE_S3 = config('USE_S3', default=False, cast=bool)
if USE_S3:
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'bucket_name': config('AWS_STORAGE_BUCKET_NAME', default='cmim-media-195275646962'),
                'region_name': config('AWS_S3_REGION_NAME', default='us-east-1'),
                # boto3 can't see .env values; hand the keys over explicitly
                'access_key': config('AWS_ACCESS_KEY_ID', default=None),
                'secret_key': config('AWS_SECRET_ACCESS_KEY', default=None),
                'querystring_auth': False,  # public bucket, clean cacheable URLs
                # Render filenames are unique per render, so there is nothing
                # to protect: overwrite=False made every save a HEAD + PUT
                'file_overwrite': True,
                'default_acl': None,
                # A render is never rewritten in place (a re-render gets a new
                # name), so clients and any CDN can keep it forever
                'object_parameters': {'CacheControl': 'public, max-age=31536000, immutable'},
                # S3-compatible stores (Cloudflare R2) and CDN domains are
                # pure configuration
                'endpoint_url': config('AWS_S3_ENDPOINT_URL', default=None),
                'custom_domain': config('AWS_S3_CUSTOM_DOMAIN', default=None),
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

# Static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Post rendering settings
POST_IMAGE_WIDTH = 800
POST_IMAGE_HEIGHT = 1200
POST_IMAGE_QUALITY = 85

# Moderation settings
BANNED_WORDS_FILE = BASE_DIR / 'banned_words.txt'
MAX_POST_LENGTH = 500

# Behind the cloudflared tunnel (dev.sh --tunnel), absolute URLs (rendered
# image links) must come back https or iOS refuses to load them
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Error reporting: no-op unless SENTRY_DSN is set (set it on the VM)
SENTRY_DSN = config('SENTRY_DSN', default='')
from sentry_sdk.scrubber import EventScrubber, DEFAULT_DENYLIST
SENTRY_SCRUBBER = EventScrubber(
    denylist=DEFAULT_DENYLIST + ['x-device-id', 'x_device_id', 'http_x_device_id', 'device_id'],
    recursive=True,
)
if SENTRY_DSN:
    import sentry_sdk
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=config('SENTRY_ENV', default='production'),
        traces_sample_rate=0.1,
        send_default_pii=False,  # semi-anonymous app: keep user data out
        # Diagnostics are declared to Apple as NOT linked to the user, so no
        # event may carry anything that ties it to an account: the device id
        # header is scrubbed, and frame locals (which hold device ids, users
        # and handles) are not captured at all.
        include_local_variables=False,
        event_scrubber=SENTRY_SCRUBBER,
    )
    # Sentry hooks logging below the handler level, so the null handler above
    # does not keep these out of it
    from sentry_sdk.integrations.logging import ignore_logger
    ignore_logger('django.security.DisallowedHost')

# Report digest emails (manage.py report_digest, cron on the VM).
# Default backend prints to stdout so the flow is testable locally;
# the VM sets EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# plus the EMAIL_HOST* credentials.
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='magazine@localhost')
REPORT_DIGEST_EMAIL = config('REPORT_DIGEST_EMAIL', default='tsargentmoore@gmail.com')

# Feature gate: image posts (backgrounds + stickers) are banked for a
# post-launch release. Matches FEATURES.imageUploads on the frontend.
ALLOW_IMAGE_POSTS = config('ALLOW_IMAGE_POSTS', default=False, cast=bool)
REVIEW_THRESHOLD = 3  # reports before a user is queued for moderator review (never an automatic ban)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/django.log',
        },
        'null': {
            'class': 'logging.NullHandler',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        # Scanners send other sites' Host headers to this box; Django already
        # answers 400. Logged as errors with a full traceback, they buried the
        # real ones.
        'django.security.DisallowedHost': {
            'handlers': ['null'],
            'propagate': False,
        },
    },
}