# Generated by Django 5.2.6 on 2025-09-13 03:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_content', models.TextField(max_length=500)),
                ('font_choice', models.CharField(choices=[('impact', 'Impact Bold'), ('mono', 'Mono Pixel'), ('rounded', 'Rounded Grotesk'), ('serif', 'Serif Punchy'), ('system', 'System Default')], default='impact', max_length=20)),
                ('font_size', models.IntegerField(default=48, help_text='Font size in pixels')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('background_color', models.CharField(default='#000000', max_length=7)),
                ('background_gradient', models.JSONField(blank=True, help_text='Gradient colors as array', null=True)),
                ('has_outline', models.BooleanField(default=False)),
                ('outline_color', models.CharField(default='#000000', max_length=7)),
                ('rendered_image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('image_width', models.IntegerField(default=800)),
                ('image_height', models.IntegerField(default=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('moderation_notes', models.TextField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('fake', 'Fake/Misleading'), ('copyright', 'Copyright Violation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('moderator_notes', models.TextField(blank=True)),
                ('action_taken', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
