# Generated by Django 5.2.6 on 2025-09-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_elements',
            field=models.JSONField(blank=True, help_text='Array of text elements with positioning and styling', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='background_color',
            field=models.CharField(default='#F8F8FF', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='font_choice',
            field=models.CharField(choices=[('arial-black', 'Arial Black'), ('impact', 'Impact Bold'), ('mono', 'Mono Pixel'), ('rounded', 'Rounded Grotesk'), ('serif', 'Serif Punchy'), ('system', 'System Default')], default='arial-black', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='font_size',
            field=models.IntegerField(default=24, help_text='Font size in pixels'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_color',
            field=models.CharField(default='#FF1A1A', max_length=7),
        ),
    ]
