# Generated by Django 5.2.6 on 2025-09-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_text_elements_alter_post_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='font_choice',
            field=models.CharField(choices=[('arial-black', 'Arial Black'), ('crimson-text', 'Crimson Text'), ('papyrus', 'Papyrus'), ('impact', 'Impact')], default='arial-black', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_color',
            field=models.CharField(default='#FF4500', max_length=7),
        ),
    ]
