# Generated by Django 5.2.6 on 2025-09-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_font_choice_alter_post_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_color',
            field=models.CharField(default='#FF1A1A', max_length=7),
        ),
    ]
