# Generated by Django 5.2.6 on 2025-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_is_repost_post_original_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bottom_y',
            field=models.IntegerField(blank=True, help_text='Bottom Y coordinate of content', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='top_y',
            field=models.IntegerField(blank=True, help_text='Top Y coordinate of content', null=True),
        ),
    ]
