# Generated by Django 5.2.6 on 2025-10-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_add_bounds_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background_image',
            field=models.TextField(blank=True, help_text='Background image URI', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='background_image_position',
            field=models.JSONField(blank=True, help_text='Background image position {x, y}', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='background_image_scale',
            field=models.FloatField(blank=True, help_text='Background image scale factor', null=True),
        ),
    ]
