# Generated by Django 5.2.6 on 2025-10-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_background_image_post_background_image_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_signed',
            field=models.BooleanField(default=False, help_text='Whether the post was published with a signature'),
        ),
        migrations.AddField(
            model_name='post',
            name='signature_style',
            field=models.CharField(blank=True, default='', help_text='Identifier for the signature preset used when the post is signed', max_length=50),
        ),
    ]
