# Generated by Django 5.2.6 on 2025-10-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_is_signed_post_signature_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sticker_elements',
            field=models.JSONField(blank=True, help_text='Array of sticker elements with positioning and scaling', null=True),
        ),
    ]
