# Generated by Django 5.2.6 on 2026-08-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_sticker_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='crop_bottom',
            field=models.IntegerField(blank=True, help_text='Crop band bottom in canvas px', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='crop_top',
            field=models.IntegerField(blank=True, help_text='Crop band top in canvas px', null=True),
        ),
    ]
