# Generated by Django 5.2.6 on 2026-08-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_crop_bottom_post_crop_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='font_choice',
            field=models.CharField(choices=[('arial-black', 'Arial Black'), ('crimson-text', 'Crimson Text'), ('papyrus', 'Papyrus'), ('impact', 'Impact'), ('courier-prime', 'Courier Prime'), ('caveat', 'Caveat')], default='arial-black', max_length=20),
        ),
    ]
