# Generated by Django 5.2.6 on 2026-08-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_font_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='response_bottom_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='response_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='response_top_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
