# Generated by Django 5.2.6 on 2026-08-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_response_bottom_y_post_response_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
