# Generated by Django 5.2.6 on 2026-09-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_notification_inbox_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_boxes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
