# Generated by Django 5.2.6 on 2026-09-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_post_content_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='canvas_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
