# Generated by Django 5.2.6 on 2026-09-25 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_post_canvas_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='original_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='posts.post'),
        ),
    ]
