# Generated by Django 5.2.6 on 2026-09-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_repost_original_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='font_choice',
            field=models.CharField(choices=[('arial-black', 'Arial Black'), ('crimson-text', 'Crimson Text'), ('papyrus', 'Papyrus'), ('impact', 'Impact'), ('courier-prime', 'Courier Prime'), ('cabin-sketch', 'Cabin Sketch'), ('freeride', 'Freeride'), ('fredericka', 'Fredericka the Great'), ('grutch-shaded', 'Grutch Shaded'), ('caveat', 'Caveat')], default='arial-black', max_length=20),
        ),
    ]
