# Generated by Django 5.2.6 on 2026-09-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_more_fonts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='font_choice',
            field=models.CharField(choices=[('arial-black', 'Arial Black'), ('crimson-text', 'Crimson Text'), ('papyrus', 'Papyrus'), ('impact', 'Impact'), ('courier-prime', 'Courier Prime'), ('cabin-sketch', 'Cabin Sketch'), ('freeride', 'Freeride'), ('fredericka', 'Fredericka the Great'), ('grutch-shaded', 'Grutch Shaded'), ('petit-formal', 'Petit Formal Script'), ('lexend-exa', 'Lexend Exa'), ('caveat', 'Caveat')], default='arial-black', max_length=20),
        ),
    ]
