# Generated by Django 5.2.6 on 2026-10-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_freeze_quote_crops'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='textless_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
