# Generated by Django 5.2.6 on 2026-10-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_textless_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
