# Generated by Django 5.2.6 on 2025-10-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_signed_posts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_signature_style',
            field=models.CharField(default='default', max_length=32),
        ),
    ]
