# Generated by Django 5.2.6 on 2026-08-30 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_default_signed_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature_color',
            field=models.CharField(blank=True, default='', help_text='Empty means auto-contrast against the post background', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='signature_font',
            field=models.CharField(default='arial-black', max_length=20),
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'blocked_user')},
            },
        ),
    ]
