# Generated by Django 5.2.6 on 2026-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_signature_color_user_signature_font_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
